# Generated by Django 5.2.3 on 2026-06-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, unique=True)),
                ('category', models.CharField(choices=[('cv', 'CV / ATS'), ('search', 'Búsqueda activa'), ('interview', 'Entrevistas'), ('networking', 'Networking / marca personal'), ('soft', 'Soft skills / negociación'), ('tech', 'Técnicas industry-specific'), ('product', 'SkilTak meta-uso'), ('wellness', 'Diversificación / wellness'), ('other', 'Otro')], default='other', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI-generated')], default='manual', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='tips_tip_is_acti_d4847f_idx')],
            },
        ),
    ]
