# Generated by Django 5.2.3 on 2026-06-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_seed_initial_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='profession_scope',
            field=models.CharField(choices=[('all', 'Todos'), ('tech', 'Tech'), ('design', 'Diseño'), ('marketing', 'Marketing'), ('sales', 'Ventas'), ('finance', 'Finanzas'), ('hr', 'RRHH'), ('operations', 'Operaciones'), ('health', 'Salud'), ('education', 'Educación'), ('legal', 'Legal')], db_index=True, default='all', max_length=20),
        ),
    ]
