# Generated by Django 5.2.3 on 2025-06-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
