# Generated by Django 5.2.3 on 2025-06-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_number_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
