# Generated by Django 5.2.3 on 2025-06-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('keywords', models.TextField(help_text='Palabras clave extraídas de los requisitos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
