# Generated by Django 5.2.3 on 2026-06-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('match', 'Match'), ('reminder', 'Reminder'), ('system', 'System'), ('company_interest', 'Company Interest')], max_length=16),
        ),
    ]
