# Generated by Django 5.2.3 on 2026-08-15 19:45

import django.db.models.deletion
import portfolio.models
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Segmento de URL público — /portafolio/<slug>.', max_length=64, unique=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('content_en', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Dueño del contenido. Solo el owner (o cualquier admin) puede editar.', on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.SlugField(help_text="Matchea `Project.id` del JSON de content (ej. 'ranktitan').", max_length=64)),
                ('image', models.ImageField(upload_to=portfolio.models._portfolio_cover_upload_path, validators=[users.models.validate_uploaded_image])),
                ('alt_text', models.CharField(blank=True, default='', help_text='Descripción para accesibilidad. Se muestra en <img alt>.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'project_id'], name='portfolio_p_portfol_df0ed4_idx')],
            },
        ),
    ]
