# Generated by Django 5.2.3 on 2026-06-25 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pageview', 'Pageview'), ('cta_click', 'CTA click'), ('outbound', 'Outbound click')], db_index=True, max_length=20)),
                ('path', models.CharField(db_index=True, max_length=200)),
                ('label', models.CharField(blank=True, db_index=True, max_length=80)),
                ('anon_id', models.CharField(db_index=True, max_length=64)),
                ('referrer', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_6c35be_idx'), models.Index(fields=['path', 'created_at'], name='analytics_a_path_27a354_idx'), models.Index(fields=['anon_id', 'created_at'], name='analytics_a_anon_id_b6930b_idx')],
            },
        ),
    ]
