# Generated by Django 5.2.3 on 2026-06-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identificador estable consumido por el frontend (snake_case).', max_length=64, unique=True)),
                ('value_bool', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Qué hace este flag. Visible para el admin en la UI.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
