# Generated by Django 5.2.3 on 2026-06-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-status_changed_at', '-applied_at', '-clicked_at']},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de confirmar'), ('applied', 'Aplicada'), ('in_review', 'En revisión'), ('interview', 'Entrevista'), ('offer', 'Oferta recibida'), ('rejected', 'Rechazada'), ('withdrawn', 'Retirada')], default='pending', max_length=12),
        ),
    ]
