# Generated by Django 5.2.3 on 2026-06-24 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_jobapplication_options_jobapplication_notes_and_more'),
        ('jobs', '0004_alter_joboffer_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title_snapshot', models.CharField(max_length=500)),
                ('offer_company_snapshot', models.CharField(blank=True, max_length=255)),
                ('offer_url_snapshot', models.URLField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('cercano', 'Cercano'), ('directo', 'Directo')], default='cercano', max_length=10)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=2)),
                ('user_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letters', to='jobs.joboffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='application_user_id_ca73aa_idx')],
                'unique_together': {('user', 'offer')},
            },
        ),
    ]
