# Generated by Django 5.2.3 on 2026-06-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_joboffer_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='portal',
            field=models.CharField(choices=[('computrabajo', 'Computrabajo'), ('weworkremotely', 'We Work Remotely'), ('elempleo', 'Elempleo'), ('infojobs', 'InfoJobs'), ('magneto', 'Magneto'), ('bumeran', 'Bumeran'), ('indeed', 'Indeed'), ('linkedin', 'LinkedIn'), ('trabajos_co', 'Trabajos Colombia'), ('hireline', 'Hireline'), ('other', 'Otro')], db_index=True, default='computrabajo', help_text='Portal de origen de la oferta', max_length=32),
        ),
    ]
