# Generated by Django 5.2.3 on 2026-06-24 04:22

from django.db import migrations, models


def backfill_country_and_modality(apps, schema_editor):
    """Pasa por todas las JobOffer existentes y rellena country + modality
    usando los mismos extractores que usan los scrapers al persistir.

    Importamos `extract_country` y `extract_modality` dentro de la
    función — Django no permite imports top-level que dependan de apps.
    `update()` por batch para no cargar todo en memoria si hay >10k rows.
    """
    from jobs.utils.offer_attributes import extract_country, extract_modality

    JobOffer = apps.get_model("jobs", "JobOffer")
    BATCH = 500
    total = 0
    qs = JobOffer.objects.all().only("id", "location", "summary")
    batch: list = []
    for offer in qs.iterator(chunk_size=BATCH):
        offer.country = extract_country(offer.location)
        offer.modality = extract_modality(offer.location, offer.summary)
        batch.append(offer)
        if len(batch) >= BATCH:
            JobOffer.objects.bulk_update(batch, ["country", "modality"])
            total += len(batch)
            batch = []
    if batch:
        JobOffer.objects.bulk_update(batch, ["country", "modality"])
        total += len(batch)
    print(f"  Backfilled {total} JobOffer rows with country + modality")


def noop_reverse(apps, schema_editor):
    # No revertible — los defaults (XX / unknown) ya están aplicados al
    # AddField, así que el reverse es no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_joboffer_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='country',
            field=models.CharField(db_index=True, default='XX', help_text="Código ISO 3166-1 alpha-2. 'XX' = desconocido", max_length=2),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='modality',
            field=models.CharField(choices=[('remote', 'Remoto'), ('hybrid', 'Híbrido'), ('onsite', 'Presencial'), ('unknown', 'Sin especificar')], db_index=True, default='unknown', help_text='Modalidad de trabajo detectada heurísticamente', max_length=10),
        ),
        migrations.RunPython(backfill_country_and_modality, noop_reverse),
    ]
