# Generated by Django 5.2.3 on 2026-06-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_add_trabajando_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
