# Generated by Django 5.2.3 on 2026-10-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_add_unavailable_ignore_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
