# Generated by Django 5.2.3 on 2026-10-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_joboffer_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='description_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
