PHONE_CODE_COUNTRY = {
  "+1": "Estados Unidos / Canadá",
  "+7": "Rusia / Kazajistán",
  "+20": "Egipto",
  "+27": "Sudáfrica",
  "+30": "Grecia",
  "+31": "Países Bajos",
  "+32": "Bélgica",
  "+33": "Francia",
  "+34": "España",
  "+36": "Hungría",
  "+39": "Italia",
  "+40": "Rumanía",
  "+41": "Suiza",
  "+44": "Reino Unido",
  "+45": "Dinamarca",
  "+46": "Suecia",
  "+47": "Noruega",
  "+48": "Polonia",
  "+49": "Alemania",
  "+51": "Perú",
  "+52": "México",
  "+53": "Cuba",
  "+54": "Argentina",
  "+55": "Brasil",
  "+56": "Chile",
  "+57": "Colombia",
  "+58": "Venezuela",
  "+60": "Malasia",
  "+61": "Australia",
  "+62": "Indonesia",
  "+63": "Filipinas",
  "+64": "Nueva Zelanda",
  "+65": "Singapur",
  "+66": "Tailandia",
  "+81": "Japón",
  "+82": "Corea del Sur",
  "+84": "Vietnam",
  "+86": "China",
  "+90": "Turquía",
  "+91": "India",
  "+92": "Pakistán",
  "+93": "Afganistán",
  "+94": "Sri Lanka",
  "+95": "Myanmar",
  "+98": "Irán",
  "+211": "Sudán del Sur",
  "+212": "Marruecos",
  "+213": "Argelia",
  "+216": "Túnez",
  "+218": "Libia",
  "+220": "Gambia",
  "+221": "Senegal",
  "+222": "Mauritania",
  "+223": "Malí",
  "+224": "Guinea",
  "+225": "Costa de Marfil",
  "+226": "Burkina Faso",
  "+227": "Níger",
  "+228": "Togo",
  "+229": "Benín",
  "+230": "Mauricio",
  "+231": "Liberia",
  "+232": "Sierra Leona",
  "+233": "Ghana",
  "+234": "Nigeria",
  "+235": "Chad",
  "+236": "República Centroafricana",
  "+237": "Camerún",
  "+238": "Cabo Verde",
  "+239": "Santo Tomé y Príncipe",
  "+240": "Guinea Ecuatorial",
  "+241": "Gabón",
  "+242": "República del Congo",
  "+243": "República Democrática del Congo",
  "+244": "Angola",
  "+245": "Guinea-Bisáu",
  "+246": "Territorio Británico del Océano Índico",
  "+248": "Seychelles",
  "+249": "Sudán",
  "+250": "Ruanda",
  "+251": "Etiopía",
  "+252": "Somalia",
  "+253": "Yibuti",
  "+254": "Kenia",
  "+255": "Tanzania",
  "+256": "Uganda",
  "+257": "Burundi",
  "+258": "Mozambique",
  "+260": "Zambia",
  "+261": "Madagascar",
  "+263": "Zimbabue",
  "+264": "Namibia",
  "+265": "Malaui",
  "+266": "Lesoto",
  "+267": "Botsuana",
  "+268": "Esuatini",
  "+269": "Comoras"
}

COUNTRY_CODES = {
    "AF": "Afghanistan",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BR": "Brazil",
    "BN": "Brunei",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo - Brazzaville",
    "CD": "Congo - Kinshasa",
    "CR": "Costa Rica",
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "SZ": "Eswatini",
    "ET": "Ethiopia",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GR": "Greece",
    "GD": "Grenada",
    "GT": "Guatemala",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HN": "Honduras",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Laos",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "MX": "Mexico",
    "FM": "Micronesia",
    "MD": "Moldova",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "MK": "North Macedonia",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",
    "QA": "Qatar",
    "RO": "Romania",
    "RU": "Russia",
    "RW": "Rwanda",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent and the Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "KR": "South Korea",
    "SS": "South Sudan",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syria",
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}