# Generated by Django 5.2.3 on 2025-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
