# Generated by Django 5.2.3 on 2026-06-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_email_alerts_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_user_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
