# Generated by Django 5.2.3 on 2026-06-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_linkedin_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.TextField(blank=True, help_text='JSON array de idiomas {language, level}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='soft_skills',
            field=models.TextField(blank=True, help_text='Habilidades blandas separadas por coma'),
        ),
    ]
