# Generated by Django 5.2.3 on 2026-06-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_totp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_improved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
