# Generated by Django 5.2.3 on 2026-06-26 01:10

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_cv_improved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('professional', 'Profesional'), ('company', 'Empresa')], db_index=True, default='professional', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visible_to_companies',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(help_text='Nombre comercial o razón social.', max_length=120)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, help_text='Sector económico (Tech, Salud, Finanzas, etc.).', max_length=80)),
                ('website', models.URLField(blank=True)),
                ('size', models.CharField(blank=True, choices=[('1-10', '1-10 empleados'), ('11-50', '11-50 empleados'), ('51-200', '51-200 empleados'), ('201-500', '201-500 empleados'), ('501-1000', '501-1000 empleados'), ('1000+', 'Más de 1000 empleados')], max_length=10)),
                ('short_description', models.CharField(blank=True, help_text='Pitch breve (140-200 chars) que ve el profesional.', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', validators=[users.models.validate_uploaded_image])),
                ('responsible_name', models.CharField(max_length=100)),
                ('responsible_role', models.CharField(help_text='Cargo (CEO, HR Lead, CTO, Recruiter, etc.).', max_length=80)),
                ('responsible_email', models.EmailField(help_text='Email del responsable. Puede coincidir con el email del User registrante o ser distinto (ej. recruiting@empresa.com).', max_length=254)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'industry'], name='users_compa_country_379c1b_idx')],
            },
        ),
    ]
