# Generated by Django 5.2.3 on 2026-06-26 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_account_type_userprofile_visible_to_companies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('dismissed', 'Descartado')], db_index=True, default='pending', max_length=10)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='users.companyprofile')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interests', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['professional', '-created_at'], name='users_compa_profess_0b2d31_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'professional'), name='unique_company_professional_interest')],
            },
        ),
    ]
