# Generated by Django 5.2.3 on 2026-07-17 12:45

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_cover_letters_generated_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=users.models._resume_upload_path, validators=[users.models.validate_uploaded_resume]),
        ),
    ]
