# Generated by Django 5.2.3 on 2026-08-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userprofile_country_userprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_skills_en',
            field=models.TextField(blank=True, default=''),
        ),
    ]
