# Generated by Django 5.2.3 on 2026-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userprofile_cv_skills_userprofile_cv_skills_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='feed_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
